version: '3'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "/wait && /app/goctr"
    stdin_open: true
    tty: true
    # volumes:
    #   - .:/app
    ports:
      - 8080:3000
    depends_on:
      - "db"
    environment:
      - WAIT_HOSTS=db:3306
      

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: godb
      MYSQL_USER: splinter
      MYSQL_PASSWORD: 0000wxyz
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    expose:
      - 3306

volumes:
  db-data:
    driver: local